# Generated by Django 4.2.5 on 2023-09-29 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_robot_quantity'),
        ('customers', '0003_remove_robotavailability_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotavailability',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='robotavailability',
            name='queued_for_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='robotavailability',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='robotavailability',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot'),
        ),
    ]
